server:
  port: 9999

spring:
  application:
    name: "configserver"

  profiles:
    #active: native
    active: git

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yosr1701/config-repo.git
          default-label: main
          clone-on-start: true

            #native:
            # search-locations: "classpath:/config"
          #search-locations: file:///C:/Users/MSI/Desktop/Devoir3/yosr-spring-cloud/config-repo

management:
  endpoint:
    web:
      exposure:
        include: '*'
